Стили для главной страницы и футер.
ssladkov/web_20201110_eshop pull request #24
Opened 2021-04-12 10:49 UTC by kovil1402

Добавил стили для главной страницы и футера

2021-04-12 19:17 UTC, ssladkov requested changes

2021-04-12 19:17 UTC, ssladkov commented on assets/css/main.scss
> +    & .grid {
& в данном случае лишний

2021-04-12 19:17 UTC, ssladkov commented on assets/css/main.scss
> +    & .grid {
и выше я у вас видел в article, уберите тоже

2021-04-12 19:17 UTC, ssladkov commented on assets/css/main.scss
> +                transform:translate(-50%, -50%);
интересный метод, но вы сильно усложнили
я бы сделал `<figure>` флекс-элементами, `<img> ` бы убрал, картинку лучше фоном в figure
текст тогда центрируется двумя строчками, без плясок с бубнами)
и когда придёт очередь адаптивности, взгляд не упадёт снова на бубны)
старайтесь выбирать наиболее простое решение, но при этом не забывать думать на перспективу

2021-04-12 19:17 UTC, ssladkov commented on assets/css/main.scss
> +                color:white;
код повторяется, если не можете выделить общий класс, тогда самое время для mixin ;)

2021-04-12 19:17 UTC, ssladkov commented on assets/css/style.scss
> +        font-size:15px;
Судя по макету, ~12px

2021-04-12 19:17 UTC, ssladkov commented on parts/footer.php
> +            <a>Новинки</a>
должно соответствовать тому, что в верхнем меню, со ссылками

2021-04-12 19:17 UTC, ssladkov commented on parts/footer.php
> +            <a>Контакты</a>
если страниц нет, то href="#"

2021-04-12 19:17 UTC, ssladkov commented on parts/footer.php
> +            <a>Все права защищены</a>
это не ссылки, возможно только inordic.ru

2021-04-12 20:03 UTC, kovil1402 commented on assets/css/main.scss
> +                transform:translate(-50%, -50%);
Танцы с бубнами обусловлены в основном моей попыткой применить grid.Если сделать картинки фоном то получается очень некрасиво при увеличении\уменьшении. =( Не знаю как сделать картинки бэкраундом но при этом чтобы они сохраняли нормальный вид при увеличении\уменьшении.

2021-04-12 20:07 UTC, ssladkov commented on assets/css/main.scss
> +                transform:translate(-50%, -50%);
background-size: cover / contain пробовали?

2021-04-12 20:54 UTC, kovil1402 commented on assets/css/main.scss
> +                transform:translate(-50%, -50%);
Да, сработало) Решение было на поверхности но я как-то перемудрил...

2021-04-13 13:47 UTC, ssladkov commented on assets/css/main.scss
> +        }
Опять повтор кода
```css
div:after,
div:before {
    content:'';
    display: block;
    position:absolute;
    width:25px;
    height:2px;
    background-color: #fff;
    left:calc(50% - 60px);
    top:19px;
}
```

2021-04-13 13:51 UTC, ssladkov approved these changes

2021-04-13 13:51 UTC, merged