Kovalenko cart functionality2
ssladkov/web_20201110_eshop pull request #35
Opened 2021-04-16 08:33 UTC by kovil1402

Пока что просто дописал метод render в cart.js и описал новый action в handlerCart.php.

2021-04-16 11:05 UTC, ssladkov commented on handlers/handlerCart.php
> +};
а это зачем? строчкой выше в подключаемом файле уже стартует сессия

2021-04-16 11:05 UTC, ssladkov commented on handlers/handlerCart.php
> +if ($action == 'render') {
вы хотите каждый продукт рендерить отдельно? в принципе можно, но не самый оптимальный вариант. Лучше выбрать из базы все товары, которые есть в корзине, сразу, например вот таким запросом (мы получаем ключи, т.е., айдишники, и сливаем их в строку разделяя запятой).
```php
$product_ids = array_keys($_SESSION['cart']);
$product_ids_str = implode(',', $product_ids);
$sql = "SELECT * FROM products WHERE id IN($product_ids_str)";
```

2021-04-16 11:33 UTC, kovil1402 commented on handlers/handlerCart.php
> +};
У меня php выдавал notice мол session is already started

2021-04-16 11:47 UTC, kovil1402 commented on handlers/handlerCart.php
> +};
Ок, я не заметил ,что вы добавили старт сессии в header_conf. Уберу тогда.

2021-04-17 20:43 UTC, kovil1402 commented
Много чего добавил!

2021-04-18 22:55 UTC, ssladkov requested changes

2021-04-18 22:55 UTC, ssladkov commented on assets/js/cart.js
> +                    amountAdd.setAttribute('style', 'height:20px;width:20px;;font-size:12px;color:white;background-color:black;cursor:pointer;margin:5px;');
через класс

2021-04-18 22:55 UTC, ssladkov commented on assets/js/cart.js
> +                    size.classList.add('size');
довольно много однотипных операций встречается таких, может это в цикле сделать? написать в массиве все свойства ходить по нему и добавлять класс (плюс доп условия), там точно нужно именно два класса? (name и name-column, например, нельзя ограничится одним name-column?)

2021-04-18 22:55 UTC, ssladkov commented on assets/js/cart.js
> +                    amountRemove.setAttribute('style', 'height:20px;width:20px;;font-size:12px;color:white;background-color:black;cursor:pointer;margin:5px;');
через класс

2021-04-18 22:55 UTC, ssladkov commented on assets/js/cart.js
> +                    delButton.setAttribute('style', 'cursor:pointer;font-size:20px');
через класс

2021-04-18 22:55 UTC, ssladkov commented on assets/js/cart.js
> +            newTable.setAttribute('style', 'display:flex;justify-content:center;align-items:center;font-size:30px');
через класс

2021-04-18 22:55 UTC, ssladkov commented on handlers/handlerCart.php
> +        $result = get_my_result($link, $sql);
непонятно, зачем здесь нужна функция? и чем вас не устроил get_db_assoc?) Подозреваю, что после
```php
$result = get_db_result_assoc($link, $sql);
```
в цикле не получилось добавить новый элемент? можно было бы использовать новый массив, или использовать символ '&' в цикле, говоря, что сам элемент может быть перезаписан
```php
foreach($result as &$product) {
  if($_SESSION['cart']["$currentId"]) {
      $product['size] = $_SESSION['cart']["$currentId"]['size'];
      $product['amount'] = $_SESSION['cart']["$currentId"]['amount'];
  }
}
```

2021-04-20 18:58 UTC, ssladkov approved these changes

2021-04-20 18:58 UTC, merged